blog/urls.py
from django.conf.urls import url

from blog import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name="archives"),
    url(r'category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    # url(r'^search/$', views.search_view, name='search')
]

comments/urls.py
from django.conf.urls import url

from comments import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.Feed import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^comment/', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls'))
]

blog/models.py
import markdown
from django.contrib.auth.models import User
from django.db import models
# 分类
from django.urls import reverse
from django.utils.html import strip_tags


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# 标签
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# 文章
class Post(models.Model):
    title = models.CharField(max_length=100)  # 标题
    body = models.TextField()  # 文章内容
    create_time = models.DateTimeField()  # 创建时间
    modified_time = models.DateTimeField()  # 最后修改时间
    excerpt = models.CharField(max_length=100, blank=True)  # 文章摘要 允许为空
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)  # 多对多关系 允许标签为空
    author = models.ForeignKey(User)  # 文章作者
    views = models.PositiveIntegerField(default=0)  # 文章浏览数

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=['markdown.extensions.extra',
                                               'markdown.extensions.codehilite', ])
            self.excerpt = strip_tags(md.convert(self.body))[:54]  # strip_tags 去掉 HTML 文本的全部 HTML 标签
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-create_time']  # 默认按照 create_time 降序排列

comments/models.py
from django.db import models


# Create your models here.
# 评论
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

blog/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from blog.models import Post, Category, Tag
from comments.forms import CommentForm
from django.views.generic import ListView, DetailView
import markdown
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
from django.db.models import Q


# 首页视图
class IndexView(ListView):
    model = Post  # 设置获取的model
    template_name = 'blog/index.html'  # 设置模板
    context_object_name = 'post_list'  # 设置返回的变量名
    paginate_by = 1  # 设置分页大小

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        # 如果没有分页, 返回空字典
        if not is_paginated:
            return {}
        left = []  # 左边连续页码
        right = []  # 右边连续页码
        left_has_more = False  # 标示第 1 页页码后是否需要显示省略号
        right_has_more = False  # 标示最后一页页码前是否需要显示省略号
        first = False  # 标示是否需要显示第 1 页的页码号
        last = False  # 标示是否需要显示最后一页的页码号
        page_number = page.number  # 用户请求的页码
        total_pages = paginator.num_pages  # 总页数
        page_range = paginator.page_range  # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        if page_number == 1:
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page_number == total_pages:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0: page_number - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            right = page_range[page_number:page_number + 2]
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0: page_number - 1]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }
        return data


# 文章视图
class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify)
        ])
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context


# 归档视图
class ArchivesView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get('year')  # 获取 url 中的year参数
        month = self.kwargs.get('month')  # 获取 url 中的month参数
        return super(ArchivesView, self).get_queryset().filter(create_time__year=year,
                                                               create_time__month=month)


# 分类视图
class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


# 云标签视图
class TagView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)


# 搜索视图
def search_view(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = '请输入关键字'
        return render(request, 'blog/index.html', {'error_msg': error_msg})
    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'error_msg': error_msg,
                                               'post_list': post_list})

templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a
                        href="{% url 'comments:post_comment' post.pk %}">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }}阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">{{ post.body | safe }}
            <div class="widget-tag-cloud">
                标签:
                {% for tag in post.tags.all %}
                    <span class="label label-important"><a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a></span>
                {% endfor %}

            </div>
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字:</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱:</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">网址:</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论:</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date" datetime="{{ comment.create_time }}">{{ comment.create_time }}</time>
                        <div class="text">{{ comment.text }}</div>
                    </li>
                {% empty %}
                    暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}

{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ post.toc | safe }}
    </div>

{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a
                            href="{% url 'blog:category' post.category.pk %}">{{ post.category }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a
                            href="{% url 'comments:post_comment' post.pk %}">{{ post.comment_set.count }} 评论</a></span>
                    <span class="views-count"><a href="#">{{ post.views }}阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="not-post">暂时没有文章发布！</div>
    {% endfor %}
    {% if is_paginated %}
        {% comment %}<div class="pagination-simple">
            {% if first %}
                <a href="?page=1">1</a>
            {% endif %}
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
            {% endif %}
            <span class="current">第{{ page_obj.number }}页/共{{ paginator.num_pages }}页</span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
            {% endif %}
        </div>{% endcomment %}
        <nav style="text-align: center">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">上一页</a></li>
                {% endif %}
                {% if first %}
                    <li><a href="?page=1">1</a></li>
                {% endif %}
                {% if left %}
                    {% if left_has_more %}
                        <li><span>...</span></li>
                    {% endif %}
                    {% for i in left %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}
                {% endif %}
                <li><a href="?page={{ page_obj.number }}" style="color: silver">{{ page_obj.number }}</a></li>
                {% if right %}
                    {% for i in right %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}
                    {% if right_has_more %}
                        <li><span>...</span></li>
                    {% endif %}
                {% endif %}
                {% if last %}
                    <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
                {% endif %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">下一页</a></li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}

{% endblock %}